---
title: "Assignment 4, Lobster"
author: "Camila Bobroff, Lydia Bleifuss"
date: "11/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(tidyverse)
library(pwr)
library(knitr)
library(plotly)
library(extrafont)
library(ggrepel)
library(kableExtra)
library(effsize)
library(dplyr)
```

```{r, include = FALSE}
lob_size_abun <- read_csv("lobster_size_abundance.csv")
lob_trap <- read_csv("lobster_traps.csv")
```
NUMBER ONE

```{r}
#Producing mean abundance by year

abun_year <- lob_size_abun %>%
  group_by(YEAR, SITE) %>% 
  filter(COUNT != "0") %>% 
  summarize(
    mean_abun = round(mean(COUNT), digits = 2)
  )
abun_year

#Producing mean trap count by year

trap_year <- lob_trap %>% 
  group_by(YEAR, SITE) %>% 
  summarize(
    mean_trap = round(mean(TRAPS), digits = 2)
  )
trap_year
```

```{r}
#Combining site rows to avoid future not working 'SITE' issues  
bind_rows(trap_year %>%  add_rownames(),
          abun_year %>% add_rownames()) %>% 
  group_by(SITE) %>% 
  summarise_all(sum)



#Creating Bubble Scatter-plot for question 1. 
abun_trap_bubble <- ggplot() +
  aes(x = trap_year$YEAR,
      y = trap_year$mean_trap,
      label = abun_year$SITE) +
  geom_point(aes(color = abun_year&SITE, size = abun_year$abun_mean)) +
  geom_text_repel(size = 3) 

abun_trap_bubble


```

NUBMER FOUR - Chi Squared

The legal minimum carapace size for lobster is 82.6 mm. What proportion of observed lobsters at each site are above the legal minimum? Does that proportion differ significantly across the 5 sites? 

```{r}
#Propper data frame 

chi_size <- lob_size_abun %>% 
  filter(COUNT != "0") %>% 
  count(SITE, SIZE) %>% 
  spread(SIZE, n) %>% 
  select(-SITE)

chi_size

#Actual proportions:

size_prop <- prop.table(as.matrix(chi_size), 1)
size_prop 

#Chi-squared 

size_x2 <- chisq.test(chi_size)
size_x2
```


